### ISSUE TITLE
Rename to harfbuzz

### ISSUE THREAD

**Issue by RazrFalcon** [manuel-rhdt/harfbuzz_rs#18]
Is it possible to drop the `_rs` suffix?

**Comment by manuel-rhdt** [comment]
I think naming it only `harfbuzz` would be confusing since this isn't the original library. Also there is already a [crate on crates.io](https://crates.io/crates/harfbuzz) named `harfbuzz`. I am however open for other naming suggestions. I agree that the `_rs` suffix is not optimal.

**Comment by RazrFalcon** [comment]
You can just add:

```toml
[lib]
name = "harfbuzz"
path = "src/lib.rs"
```

to `Cargo.toml`, so it will became just `harfbuzz` in a code.

**Comment by manuel-rhdt** [comment]
Won't this interfere with the name shown on crates.io?

**Comment by RazrFalcon** [comment]
Nope. Because crates.io show the package name, not a library.

It pretty popular. [xml-rs](https://github.com/netvl/xml-rs/blob/ffe8d3e7b9977089d3679b1301294111c90c2355/Cargo.toml#L12) does this too, for example. So it's a common thing.

**Comment by manuel-rhdt** [comment]
Since this would be a breaking change and I don't want to release version 2.0 just for a rename, I will reconsider this issue when a version 2.0 is going to be releases.

In the meantime I suggest renaming the dependency in your own `Cargo.toml` as shown [in the cargo docs](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#renaming-dependencies-in-cargotoml) to avoid typing `_rs`.

**Comment by RazrFalcon** [comment]
I see. No problem.
